:toc-placement!:
:imagesdir: .

== Глава 1. Ваша первая программа на языке Java

В наши дни люди все больше времени тратят на общение с компьютерами, смартфонами или планшетами, нежели с другими людьми. Уже стало обычным делом, когда мы говорим друг другу: "Я установил классное приложение, которое может делать и то и другое". То есть, для взаимодействия с компьютерной техникой люди используют приложения или, по-другому, программы. И ведь кто-то написал эти приложения! Так вот, того кто пишет приложения для компьютеров обычно называют программистом или разработчиком программного обеспечения.

Программисты пишут различные приложения, например, игры, калькуляторы или текстовые редакторы. Без приложений компьютеры, смартфоны или игровые приставки для большинства людей будут абсолютно не нужны. Любое компьютерное устройство обычно уже имеет установленную операционную систему такую, как Windows, Mac OS, iOS или Android. Однако давайте представим смартфон без приложений или компьютер, который может показывать только логотип операционной системы. Кому будут нужны такие устройства? 

Программисты создают приложения с помощью различных языков программирования, например, с помощью Java, Python, C++, JavaScript, C или множества других языков. Некоторые из этих языков хорошо подходят для разработки маленьких программ, для которых требуется совсем небольшое количество памяти и которые могут быть зашиты прямо в компьютерные микросхемы. Другие языки программирования отлично справляются с программами для Интернет. Эти программы запускаются в интернет-браузерах. Еще есть языки для программ, работающих на больших серверах и обслуживающих тысячи пользовательских запросов. Даже есть языки, которые заточены для создания прекрасных графических изображений. Также как и языки, на которых говорят люди, языки программирования имеют наборы слов (их часто называют ключевыми словами) и правила использования этих слов (это - синтаксис).

С помощью этой книги вы изучите синтаксис языка Java, который может использоваться для разработки наибольшего количества типов приложений. На протяжении многих лет язык программирования Java является одним из самых популярных в мире языков. В то время, когда я пишу эти строки, в мире насчитывается более десяти миллионов профессиональных Java-программистов. Что же делает этот язык таким популярным?

В первую очередь это то, что одна и та же Java-программа может выполняться на различных устройствах: на настольных компьютерах под управлением Windows или MacOS, на смартфонах или планшетах. Собственно говоря, для Java-программам не имеет значения на каком именно устройстве они запущены, потому что они выполняются в виртуальной среде, которая называется виртуальной машиной. О виртуальной машине Java мы поговорим немного позже.

Java может быть встроена в маленькие микросхемы, которые контролируют работу различной бытовой техники или промышленных устройств. Например, такие микросхемы как те, что управляют умными домами, где отопление или освещение может быть запрограммировано удаленно с помощью телефона. Любые вещи, имеющие соединение с Интернет, могут программироваться на языке Java.

Некоторые языки программирования могут иметь общие принципы построения программ. Язык Java мы называем объектно-ориентированным. Его программные элементы (_классы_) представляют объекты реального мира. Например, вы можете создать класс под названием `Car` и определить для него атрибуты, присущие настоящей машине: двери, колеса и так далее. Затем вы можете создать другой класс на основе класса `Car`. Пусть это будет класс `Tesla`, который обладает всеми свойствами класса `Car` (двери, колеса) плюс электромотор.

Еще можно добавить, что программное обеспечение, необходимое для написания Java-программ бесплатно. Также в мире есть огромное количество профессиональных программистов на Java. Вы сможете найти массу примеров, а если вы столкнетесь с проблемой, вы всегда сможете найти решение на каком-нибудь популярном интернет-форуме, например, на http://stackoverflow.com[Stack Overflow]. Будьте уверены, кто-нибудь точно ответит.

Однако хватит рассуждать! Давайте начнем изучать Java.


=== Процесс установки Java на Ваш компьютер.

Чтобы начать программировать на Java вы должны загрузить Java Development Kit (JDK) с сайта компании, которая называется Oracle и выпускает новые релизы или обновления версий языка Java.