:toc:
:toclevels: 4
:imagesdir: ./

== Глава 1. Ваша первая программа на языке Java

Люди общаются друг с другом на различных языках. Также и программисты пишут компьютерные игры, калькуляторы, текстовые редакторы и прочие компьютерные программы с использованием различных языков. Без программ экраны ваших компьютеров, смартфонов и игровых приставок будут всегда темными. Все эти устройства называются _железо_, а программы для них это _программное обеспечение_.

На протяжении многих лет язык Java остается самым популярным языком в мире. Чтобы убедиться в этом достаточно взглянуть на http://www.tiobe.com/content/paperinfo/tpci/index.html[индекс популярности Tiobe]. Я не знаю точно когда именно вы откроете этот рейтинг, но могу поспорить, что язык Java будет в тройке самых популярных языков. Что же делает язык Java таким привлекательным?

Во-первых, одна и та же Java-программа может быть _выполнена_ (или запущена) на различных устройствах, например, на персональном компьютере, на ноутбуке или на суперЭВМ. По сути, Java-программа не знает на каком именно устройстве она запущена, потому что она выполняется с помощью специального программного обеспечения. Это программное обеспечение называется виртуальная машина Java (Java Virtual Machine или JVM). Предположим, что программе необходимо напечатать сообщение. Для выполнения этого действия она обращается к виртуальной машине, которая знает как нужно работать с принтером.

Во-вторых, на языке Java можно писать программы для мобильных устройств - смартфонов, планшетов и т.п.

В-третьих, Java-программы могут встраиваться в микроконтроллеры бытовой техники или промышленных роботов. Возможно вы уже слышали об умных домах, которые позволяют удаленно управлять отоплением или освещением с помощью смартфона. В скором будущем даже чайник будет автоматически начинать кипятить воду по сигналу будильника на вашем телефоне. Для всего этого существует специальный термин - "интернет вещей". И эти вещи могут быть запрограммированы на языке Java.

В-четвертых, изучать Java не очень сложно, потому что это _объектно-ориентированный_ язык. Основными программными элементами Java являются _классы_, которые описывают объекты реального мира. Например, вы можете создать класс под названием `Автомобиль` и определить для него атрибуты, такие как двери или колеса, в точности как у настоящего автомобиля. После этого на основе класса `Автомобиль` вы можете создать другой класс, например, класс `Тесла`, который будет иметь все атрибуты, присущие обычному автомобилю (двери, колеса, корпус), плюс нечто специфическое только для машин марки Тесла (электро двигатель).

В-пятых, Java-программа, запущенная на сервере, может обрабатывать запросы тысячей пользователей. Такие программы могут работать используя одновременно несколько процессоров или даже несколько серверов. Например, http://www.forbes.com/sites/michaelkanellos/2013/03/21/ebays-mpg-for-data-centers/[сайт eBay] работает на тысячах серверов _параллельно_ и на многих из этих серверов выполняются Java-программы.

В-шестых, изначально программное обеспечение, необходимое для написания программ на Java, было бесплатным. Поэтому на сегодняшний день в мире существует более девяти миллионов профессиональных программистов на этом языке. Они выкладывают в интернет массу примеров и других полезных материалов по программированию на языке Java. Если вы столкнетесь с какой-нибудь проблемой, вы легко сможете найти решение с помощью поиска в сети или задать интересующие вас вопросы на специальных программистских форумах, таких как http://stackoverflow.com/questions/tagged/java[Stack Overflow]. Будьте уверены, что вам обязательно ответят!

Этот список можно продолжать бесконечно. Кроме всего прочего, если вы решили стать программистом, учтите, что навыки программирования на языке Java очень востребованы в этой индустрии. Однако, хватит болтать! Давайте установим Java на компьютер и начнем изучать это язык.

=== Процесс установки Java
